version: 2
updates:

  - package-ecosystem: docker
    commit-message:
      prefix: chore
    directory: /
    schedule:
      interval: monthly
    reviewers:
      - "mendersoftware/client-dependabot-reviewers"
